from flask.ext import restful

CONFIG = {
    "LOGDIR" :  "../logs/", 
    "USER" :    "ubuntu",
    "DISPLAY" : ":1",
    "PORT" : "/dev/ttyACM0",

    "COMMANDS" : [
        {"name" : "Restart Signs",
         "url"  : "restart-signs",
         "cmd"  : "../bin/reset-signs",
         "type" : "button",
         "group": "Signs",
         "args" : [{"name":"room-url","hidden":True}]},
        {"name" : "Start Stream",
         "url"  : "start-stream",
         "cmd"  : "../bin/start-stream",
         "group": "Overflow Streaming",
         "type" : "select","args" : [{"name":"camera-url","label":"Camera URL"}]},
        {"name" : "Stop Stream",
         "url"  : "stop-stream",
         "cmd"  : "../bin/stop-stream",
         "group": "Overflow Streaming",
         "type" : "button"},
        {"name" : "Start Recording",
         "url"  : "record-start",
         "cmd"  : "../bin/start-record",
         "group": "Recording",
         "type" : "button"},
        {"name" : "Stop Recording",
         "url"  : "record-stop",
         "cmd"  : "../bin/stop-record",
         "group": "Recording",
         "type" :"button"}
    ],
    "PINS" : [
        {"name" :"Scan Leff",
         "url"  :"scan-left",
         "pin"  :5,
         "type" :"button",
         "group": "Scan",
         "args" :[{"name":"cycle","hidden":True}]},
        {"name": "Scan Right",
         "url"  :"scan-right",
         "pin"  :6,
         "type" :"button",
         "group": "Scan",
         "args" :[{"name":"cycle","hidden":True}]},
        {"name" :"Scan Down",
         "url"  :"scan-down",
         "pin"  :4,
         "type" :"button",
         "group": "Scan",
         "args" :[{"name":"cycle","hidden":True}]},
        {"name" : "Scan Up",
         "url"  :"scan-up",
         "pin"  :3,
         "type" :"button",
         "group": "Scan",
         "args" :[{"name":"cycle","hidden":True}]},
        {"name" :"Scan Menu",
         "url"  :"scan-menu",
         "pin"  :2,
         "type" :"button",
         "group": "Scan",
         "args" :[{"name":"cycle","hidden":True}]},
        {"name" :"Scan Zoom",
         "url"  :"scan-zoom",
         "pin"  :1,
         "type" :"button",
         "group": "Scan",
         "args" :[{"name":"cycle","hidden":True}]},
        {"name" :"KVM Side",
         "url"  :"kvm-read",
         "pin"  :7,
         "type" :"read",
         "group":"KVM"},
        {"name" :"Switch KVM",
         "url"  :"kvm-switch",
         "pin"  :0,
         "type" :"button",
         "group": "KVM",
         "args" :[{"name":"cycle","hidden":True}]}
    ]
}

class Config(restful.Resource):
    def get(self):
        '''
        Returns the configuration
        '''
        return CONFIG
